project:
  type: manuscript
  execute-dir: project
manuscript:
  article: index.qmd
# notebooks:
#   - notebook: notebooks/equations.qmd

execute:
  freeze: auto
csl: _extensions/quarto-journals/agu/nature-medicine.csl
format:
  # html:
  #   toc: true
  #   comments:
  #     hypothesis: true
  # docx:
  #   toc: false
  #   notebook-links: false
  # agu-pdf:
  #   execute:
  #       message: false
  #       warning: false
  #   header-includes:
  #     - \usepackage{annotate-equations}
  pdf:
    documentclass: article
    linestretch: 1.5
    margin-left: 1in
    margin-right: 1in
    margin-top: 1in
    margin-bottom: 1in
    dpi: 100
    execute:
        warning: false
    header-includes:
      - \usepackage{annotate-equations}
      - \usepackage{lineno}
      - \linenumbers
  # agu-pdf:
  #   dpi: 200
  #   notebook-links: false
  #   header-includes:
  #     - \usepackage{annotate-equations}
  # nature-pdf:
  #   execute:
  #     message: false
  #     warning: false
  #   header-includes:
  #     - \usepackage{annotate-equations}








